INSERT INTO PIHISTORYCATEGORY
	("ID", "NAME")
VALUES
	(1, 'Kategorie 1');
	
INSERT INTO PIHISTORYCATEGORY
	("ID", "NAME")
VALUES
	(2, 'Kategorie 2');
	
INSERT INTO PIHISTORYCATEGORY
	("ID", "NAME")
VALUES
	(3, 'Kategorie 3');