-- INSERT MONETARY UNITS               --
-- Warning: No exchange rates included --
-- EUR (Euro) is the reference unit    --

INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('AED', 'United Arab Emirates dirham', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('AFN', 'Afghan afghani', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('ALL', 'Albanian lek', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('AMD', 'Armenian dram', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('ANG', 'Netherlands Antillean guilder', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('AOA', 'Angolan kwanza', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('ARS', 'Argentine peso', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('AUD', 'Australian dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('AWG', 'Aruban florin', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('AZN', 'Azerbaijani manat', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('BAM', 'Bosnia and Herzegovina convertible mark', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('BBD', 'Barbados dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('BDT', 'Bangladeshi taka', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('BGN', 'Bulgarian lev', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('BHD', 'Bahraini dinar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('BIF', 'Burundian franc', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('BMD', 'Bermudian dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('BND', 'Brunei dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('BOB', 'Boliviano', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('BOV', 'Bolivian Mvdol (funds code)', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('BRL', 'Brazilian real', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('BSD', 'Bahamian dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('BTN', 'Bhutanese ngultrum', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('BWP', 'Botswana pula', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('BYR', 'Belarusian ruble', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('BZD', 'Belize dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('CAD', 'Canadian dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('CDF', 'Congolese franc', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('CHE', 'WIR Bank (complementary currency) CHE', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('CHF', 'Swiss franc', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('CHW', 'WIR Bank (complementary currency) CHW', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('CLF', 'Unidad de Fomento (funds code)', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('CLP', 'Chilean peso', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('CNY', 'Chinese yuan', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('COP', 'Colombian peso', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('COU', 'Unidad de Valor Real', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('CRC', 'Costa Rican colon', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('CUC', 'Cuban convertible peso', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('CUP', 'Cuban peso', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('CVE', 'Cape Verde escudo', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('CZK', 'Czech koruna', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('DJF', 'Djiboutian franc', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('DKK', 'Danish krone', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('DOP', 'Dominican peso', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('DZD', 'Algerian dinar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('EEK', 'Estonian kroon', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('EGP', 'Egyptian pound', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('ERN', 'Eritrean nakfa', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('ETB', 'Ethiopian birr', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('EUR', 'Euro', 1, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('FJD', 'Fiji dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('FKP', 'Falkland Islands pound', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('GBP', 'Pound sterling', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('GEL', 'Georgian lari', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('GHS', 'Ghanaian cedi', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('GIP', 'Gibraltar pound', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('GMD', 'Gambian dalasi', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('GNF', 'Guinean franc', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('GTQ', 'Guatemalan quetzal', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('GYD', 'Guyanese dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('HKD', 'Hong Kong dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('HNL', 'Honduran lempira', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('HRK', 'Croatian kuna', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('HTG', 'Haitian gourde', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('HUF', 'Hungarian forint', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('IDR', 'Indonesian rupiah', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('ILS', 'Israeli new sheqel', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('INR', 'Indian rupee', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('IQD', 'Iraqi dinar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('IRR', 'Iranian rial', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('ISK', 'Icelandic króna', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('JMD', 'Jamaican dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('JOD', 'Jordanian dinar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('JPY', 'Japanese yen', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('KES', 'Kenyan shilling', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('KGS', 'Kyrgyzstani som', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('KHR', 'Cambodian riel', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('KMF', 'Comoro franc', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('KPW', 'North Korean won', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('KRW', 'South Korean won', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('KWD', 'Kuwaiti dinar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('KYD', 'Cayman Islands dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('KZT', 'Kazakhstani tenge', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('LAK', 'Lao kip', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('LBP', 'Lebanese pound', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('LKR', 'Sri Lanka rupee', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('LRD', 'Liberian dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('LSL', 'Lesotho loti', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('LTL', 'Lithuanian litas', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('LVL', 'Latvian lats', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('LYD', 'Libyan dinar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('MAD', 'Moroccan dirham', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('MDL', 'Moldovan leu', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('MGA', 'Malagasy ariary', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('MKD', 'Macedonian denar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('MMK', 'Myanma kyat', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('MNT', 'Mongolian tugrik', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('MOP', 'Macanese pataca', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('MRO', 'Mauritanian ouguiya', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('MUR', 'Mauritian rupee', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('MVR', 'Maldivian rufiyaa', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('MWK', 'Malawian kwacha', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('MXN', 'Mexican peso', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('MXV', 'Mexican Unidad de Inversion (UDI) (funds code)', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('MYR', 'Malaysian ringgit', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('MZN', 'Mozambican metical', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('NAD', 'Namibian dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('NGN', 'Nigerian naira', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('NIO', 'Cordoba oro', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('NOK', 'Norwegian krone', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('NPR', 'Nepalese rupee', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('NZD', 'New Zealand dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('OMR', 'Omani rial', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('PAB', 'Panamanian balboa', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('PEN', 'Peruvian nuevo sol', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('PGK', 'Papua New Guinean kina', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('PHP', 'Philippine peso', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('PKR', 'Pakistani rupee', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('PLN', 'Polish złoty', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('PYG', 'Paraguayan guaraní', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('QAR', 'Qatari rial', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('RON', 'Romanian new leu', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('RSD', 'Serbian dinar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('RUB', 'Russian rouble', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('RWF', 'Rwandan franc', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('SAR', 'Saudi riyal', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('SBD', 'Solomon Islands dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('SCR', 'Seychelles rupee', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('SDG', 'Sudanese pound', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('SEK', 'Swedish krona/kronor', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('SGD', 'Singapore dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('SHP', 'Saint Helena pound', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('SLL', 'Sierra Leonean leone', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('SOS', 'Somali shilling', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('SRD', 'Surinamese dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('STD', 'São Tomé and Príncipe dobra', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('SYP', 'Syrian pound', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('SZL', 'Lilangeni', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('THB', 'Thai baht', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('TJS', 'Tajikistani somoni', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('TMT', 'Turkmenistani manat', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('TND', 'Tunisian dinar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('TOP', 'Tongan paʻanga', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('TRY', 'Turkish lira', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('TTD', 'Trinidad and Tobago dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('TWD', 'New Taiwan dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('TZS', 'Tanzanian shilling', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('UAH', 'Ukrainian hryvnia', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('UGX', 'Ugandan shilling', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('USD', 'United States dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('USN', 'United States dollar (next day) (funds code)', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('USS', 'United States dollar (same day) (funds code)', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('UYU', 'Uruguayan peso', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('UZS', 'Uzbekistan som', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('VEF', 'Venezuelan bolívar fuerte', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('VND', 'Vietnamese đồng', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('VUV', 'Vanuatu vatu', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('WST', 'Samoan tala', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('XAF', 'CFA franc BEAC', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('XAG', 'Silver (one troy ounce)', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('XAU', 'Gold (one troy ounce)', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('XBA', 'European Composite Unit (EURCO)', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('XBB', 'European Monetary Unit (E.M.U.-6)', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('XBC', 'European Unit of Account 9 (E.U.A.-9)', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('XBD', 'European Unit of Account 17 (E.U.A.-17)', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('XCD', 'East Caribbean dollar', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('XDR', 'Special Drawing Rights', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('XFU', 'UIC franc (special settlement currency)', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('XOF', 'CFA Franc BCEAO', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('XPD', 'Palladium (one troy ounce)', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('XPF', 'CFP franc', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('XPT', 'Platinum (one troy ounce)', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('XTS', 'Code reserved for testing purposes', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('XXX', 'No currency', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('YER', 'Yemeni rial', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('ZAR', 'South African rand', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('ZMK', 'Zambian kwacha', 0, 1);
INSERT INTO MonetaryUnit (id, name, reference, factor) VALUES ('ZWL', 'Zimbabwe dollar', 0, 1);

